---
title: "AOO_EOO_workflow"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
library(raster) ### NOTE: attach this BEFORE tidyverse
library(tidyverse)
library(here)
library(sf) # simple features package (for shapefiles)
library(janitor)

# IUCN Red List of Ecosystems Analysis
# https://cran.r-project.org/web/packages/redlistr/vignettes/redlistr-vignette.html
library(rgeos)
library(rgdal)
library(redlistr)
```


```{r}

# --- open SB ecosystems raster and SB shapefile

sb_ecos <- raster(here("sb_ecosystems.tif")) 
sb_shp <- st_read(here("sb-county-boundary",
                       "data",
                       "commondata",
                       "county_boundaries",
                       "SB_only.shp")) 

#plot(sb_ecos)
```
```{r}


oak_savanna <- sb_ecos == 65
plot(oak_savanna)

crs(oak_savanna)@projargs
crs(sb_shp)@projargs

proj_oak_savanna <- projectRaster(oak_savanna,crs=crs(sb_shp))
crs(proj_oak_savanna)@projargs

area2020 <- getArea(proj_oak_savanna)
```

```{r}
df_oak_savanna <- as.data.frame(oak_savanna, xy = TRUE)

df_oak_savanna %>% 
  group_by(layer) %>%
  summarise(num_pixels = length(layer))


df_proj_oak_savanna <- as.data.frame(proj_oak_savanna, xy = TRUE)
head(df_proj_oak_savanna)

unique(df_proj_oak_savanna$layer)

df_proj_oak_savanna %>% 
  group_by(layer) %>%
  summarise(num_pixels = length(layer))
```



```{r}
# --- make sub-raster with selected ecosystem 
# ex: 65 = Southern California Oak Woodland and Savanna

# select_ecosytem <- function(n_ecosystem, make_binary=FALSE){
#   # assumes ecosystem code exists
#   eco_raster <- sb_ecos == n_ecosystem 
#   if(make_binary == TRUE){
#     values(eco_raster)[values(eco_raster) != 1] <- NA
#     return(eco_raster)
#   }
#   return(eco_raster)
# }
# --------------------------------------------------------

# oak_savanna <- select_ecosytem(65,TRUE)
# plot(oak_savanna)


# --- reproject if necessary 
# redlistr needs rasters to be in projected crs, not in LonLat
# projected_crs <- function(raster_inst,has_projected){
#   if(isLonLat(raster_inst) == TRUE){
#     return(projectRaster(raster_inst,crs=crs(has_projected)))
#   }
#   return(raster_inst)
# }
# # --------------------------------------------------------
# 
# 
# crs(sb_shp)@projargs
# if(isLonLat(sb_shp) == FALSE){
#   oak_savanna <- projected_crs(oak_savanna,sb_shp)
# }
# 
# isLonLat(oak_savanna)

```
```{r}
area_2020 <- getArea(oak_savanna)
area_2020
```

